// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package status

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson727fe99aDecodeRegistryCleanerAgentInternalPkgStatus(in *jlexer.Lexer, out *Status) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "alive":
			out.IsAlive = bool(in.Bool())
		case "unusedBlobs":
			out.UnusedBlobs = int(in.Int())
		case "blobsCleanedAt":
			out.BlobsCleanedAt = string(in.String())
		case "blobsIndexedAt":
			out.BlobsIndexedAt = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson727fe99aEncodeRegistryCleanerAgentInternalPkgStatus(out *jwriter.Writer, in Status) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"alive\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.IsAlive))
	}
	{
		const prefix string = ",\"unusedBlobs\":"
		out.RawString(prefix)
		out.Int(int(in.UnusedBlobs))
	}
	{
		const prefix string = ",\"blobsCleanedAt\":"
		out.RawString(prefix)
		out.String(string(in.BlobsCleanedAt))
	}
	{
		const prefix string = ",\"blobsIndexedAt\":"
		out.RawString(prefix)
		out.String(string(in.BlobsIndexedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Status) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson727fe99aEncodeRegistryCleanerAgentInternalPkgStatus(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Status) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson727fe99aEncodeRegistryCleanerAgentInternalPkgStatus(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Status) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson727fe99aDecodeRegistryCleanerAgentInternalPkgStatus(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Status) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson727fe99aDecodeRegistryCleanerAgentInternalPkgStatus(l, v)
}
