stages:
  - build
variables:
  GIT_CLONE_PATH: '$CI_BUILDS_DIR/$CI_PROJECT_NAME'
build:
  stage: build
  script:
    - sudo docker-compose up -d
    - sudo chown -R gitlab-runner:gitlab-runner /home/download/qoollo-registry-cleaner-agent/
    - echo "Готово"
  only:
    - dev
  tags:
    - agent-runner
