stages:
  - build
variables:
  GIT_CLONE_PATH: '$CI_BUILDS_DIR/$CI_PROJECT_NAME'
build:
  stage: build
  script: 
    - go build -o build/agent -v ./cmd
    - sudo sed -i '7s/5555/5000/' /home/download/qoollo-registry-cleaner-agent/config/agent.toml
    - sudo systemctl restart agent-registry
    - sudo chown -R gitlab-runner:gitlab-runner /home/download/
    - echo "Готово"
  only:
    - dev
  tags:
    - agent-runner
