bind_addr = ":3000"
cors_allowed_origins = [ "*" ]
cors_allowed_headers = ["Accept", "Content-Type", "Content-Length", "Accept-Encoding", "Docker-Content-Digest", "Etag"]
cors_exposed_headers = [ "*" ]
bitcask_storage_path = "bitcask-storage"
gc_index_schedule = "0 */15 * ? * *"
gc_removal_schedule = "0 0 3 * * ?"
registry_api_url = "http://localhost:5000"
registry_container_name = "registry"
registry_mount_point = "/mnt/registry"
registry_config_path = "/etc/docker/registry/config.yml"
