bind_addr = ":3000"
cors_allowed_origins = [ "*" ]
bitcask_storage_path = "bitcask-storage"
gc_schedule = "0 0 3 * * ?"
registry_api_url = "http://localhost:5555"
registry_container_name = "registry"
registry_mount_point = "/mnt/registry"
registry_config_path = "/etc/docker/registry/config.yml"
